// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using HardwareControllers;
using Internal;

namespace CS6021
{
	public partial class ViewCtrl_Memory : UIViewController
	{
		public List<Memory> memories = new List<Memory>();
		private int currentMemoryInstanceListIndex = 0;

		public ViewCtrl_Memory (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			led_extern_img.Hidden = true;
			led_off_img.Hidden = true;
			led_input_img.Hidden = true;
			led_end_img.Hidden = true;
			led_clear_img.Hidden = true;

			//TODO: Initially put one instance if apps runs for the first time
			memories.Add(new Memory("Hbf"));

			tblVw_Memory.Source = new TableSourceMemory(memories);
			Add(tblVw_Memory);
			((TableSourceMemory)tblVw_Memory.Source).MemorySelected += ViewController_MemorySelected;

			btn_memory_add.Clicked += btn_memory_add_EventHandler;
		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			// Release any cached data, images, etc that aren't in use.
		}

		/*--------------------------------------------------------------------*/

		void ViewController_MemorySelected(object sender, int currentMemoryListIndex)
		{
			currentMemoryInstanceListIndex = currentMemoryListIndex;
		}

		private void btn_memory_add_EventHandler(object sender, EventArgs args)
		{
			memories.Add(new Memory());
			tblVw_Memory.ReloadData();
		}

		/*--------------------------------------------------------------------*/

		partial void btn_A1_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(1);
		}

		partial void btn_A2_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(2);
		}

		partial void btn_A3_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(3);
		}

		partial void btn_A4_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(4);
		}

		partial void btn_A5_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(5);
		}

		partial void btn_A6_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(6);
		}

		partial void btn_A7_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(7);
		}

		partial void btn_A8_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(8);
		}

		partial void btn_B1_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(9);
		}

		partial void btn_B2_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(10);
		}

		partial void btn_B3_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(11);
		}

		partial void btn_B4_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(12);
		}

		partial void btn_B5_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(13);
		}

		partial void btn_B6_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(14);
		}

		partial void btn_B7_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(15);
		}

		partial void btn_B8_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(16);
		}

		partial void btn_C1_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(17);
		}

		partial void btn_C2_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(18);
		}

		partial void btn_C3_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(19);
		}

		partial void btn_C4_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(20);
		}

		partial void btn_C5_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(21);
		}

		partial void btn_C6_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(22);
		}

		partial void btn_C7_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(23);
		}

		partial void btn_C8_pressed(UIButton sender)
		{
			memories[currentMemoryInstanceListIndex].SetRoute(24);
		}

		/*--------------------------------------------------------------------*/

		partial void btn_extern_pressed(UIButton sender)
		{
		}

		partial void btn_off_pressed(UIButton sender)
		{
		}

		partial void btn_input_pressed(UIButton sender)
		{
		}

		partial void btn_end_pressed(UIButton sender)
		{
		}

		//partial void btn_edit_pressed(UIButton sender)
		//{
		//}

		partial void btn_clear_pressed(UIButton sender)
		{
		}
	}
}
